---
label: Project
hide_body: false
fields:
- type: datetime
  name: date
  label: Date
  default: now
- type: text
  name: title
  label: Title
- type: text
  name: author
  label: Author
- type: text
  name: github_url
  label: Github URL
- type: text
  name: demo_url
  label: Demo URL
- type: text
  name: posttype
  label: Post Type
  default: project
  hidden: true
- type: list
  name: skills
  label: Skills
- type: file
  name: hero_image
  label: Hero Image
